/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  prefix: "aic-",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#f5f3ff",
          100: "#ede9fe",
          200: "#ddd6fe",
          300: "#c4b5fd",
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
          700: "#6d28d9",
          800: "#5b21b6",
          900: "#4c1d95",
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
  safelist: [
    "aic-fixed",
    "aic-bottom-0",
    "aic-left-1/2",
    "aic--translate-x-1/2",
    "aic-w-[50vw]",
    "aic-p-4",
    "aic-bg-white",
    "aic-shadow-lg",
    "aic-border-t",
    "aic-border-gray-200",
    "aic-mb-4",
    "aic-transition-all",
    "aic-duration-300",
    "aic-opacity-0",
    "aic-h-0",
    "aic-overflow-hidden",
    "aic-relative",
    "aic-bg-gray-100",
    "aic-rounded-lg",
    "aic-absolute",
    "aic-top-2",
    "aic-right-2",
    "aic-text-gray-500",
    "hover:aic-text-gray-700",
    "aic-transition-colors",
    "aic-p-1",
    "aic-h-5",
    "aic-w-5",
    "aic-pr-8",
    "aic-flex",
    "aic-flex-col",
    "aic-gap-2",
    "aic-top-3",
    "aic-left-3",
    "aic-px-10",
    "aic-py-3",
    "aic-border",
    "aic-resize-none",
    "focus:aic-outline-none",
    "focus:aic-ring-2",
    "focus:aic-ring-primary-500",
    "focus:aic-border-transparent",
    "placeholder:aic-text-gray-400",
    "aic-min-h-[50px]",
    "aic-max-h-[120px]",
    "aic-hidden",
    "aic-right-3",
    "aic-animate-spin",
    "aic-text-primary-600",
    "aic-opacity-25",
    "aic-opacity-75",
    "aic-animate-bounce",
    "aic-space-x-3",
    "aic-items-center",
    "aic-justify-center",
    "aic-h-2",
    "aic-w-2",
    "aic-bg-primary-400",
    "aic-rounded-full",
    "aic-hidden",
    "aic-animate-spin",
    "aic-opacity-25",
    "aic-opacity-75",
    "aic-text-primary-600",
  ],
};
